name: Auto Deploy

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull Latest Changes
        run: git pull origin main

      - name: Restart Render Server
        run: curl -X POST "https://api.render.com/deploy/webhook/your-webhook-id"
